
-- Update existing user profile to look better
UPDATE profiles SET full_name = 'Fatima Ahmed', tier = 'Gold', points_total = 1890 WHERE user_id = '11d01395-18e8-4ba6-a05e-64574e7fba35';

-- Insert sample discussions
INSERT INTO discussions (user_id, title, body, category, views, points) VALUES
('11d01395-18e8-4ba6-a05e-64574e7fba35', 'First-time Hajj tips and advice', 'Assalamu alaikum! I''m planning my first Hajj next year and would love to hear advice from those who have completed it. What should I know about preparation, what to pack, and what to expect during the journey? Any tips for first-timers would be greatly appreciated!', 'Hajj Preparation', 312, 10),
('11d01395-18e8-4ba6-a05e-64574e7fba35', 'Monthly savings challenge - Join us!', 'Starting a group challenge to save $200/month together. Who''s in? We can share tips and keep each other motivated! I''ve been saving for 6 months now and the accountability really helps. Let''s create a supportive community around our savings goals.', 'Savings Tips', 189, 10),
('11d01395-18e8-4ba6-a05e-64574e7fba35', 'Best duas to recite during Hajj', 'I''ve compiled a list of important duas for different parts of the Hajj journey. Would love to hear what others recommend. From Talbiyah to the duas at Arafat, Muzdalifah, and during Tawaf - sharing is caring! Let''s build a comprehensive collection together.', 'Spiritual Guidance', 421, 10),
('11d01395-18e8-4ba6-a05e-64574e7fba35', 'Package comparison: Essential vs Premium', 'Has anyone done both packages? Trying to decide if the Premium is worth the extra $1000. What are the main differences in accommodation, meals, and overall experience? Would love honest reviews from people who have tried either package.', 'Travel Planning', 156, 10),
('11d01395-18e8-4ba6-a05e-64574e7fba35', 'Fundraising ideas for Hajj savings', 'Sharing some creative fundraising ideas that helped me reach my goal faster. Bake sales, online fundraisers, community events, and more! These strategies helped me save an additional $2000 in just 3 months. Happy to share detailed plans with anyone interested.', 'Savings Tips', 203, 10),
('11d01395-18e8-4ba6-a05e-64574e7fba35', 'Health and fitness prep for Hajj', 'Starting a fitness routine to prepare for the physical demands of Hajj. Anyone want to share their workout plans? The walking alone can be 10-15km per day, so building endurance is crucial. Let''s discuss nutrition, exercise routines, and health tips.', 'Hajj Preparation', 98, 10),
('11d01395-18e8-4ba6-a05e-64574e7fba35', 'My Hajj journey - A success story', 'Alhamdulillah, I completed my Hajj last year after saving for 3 years through this platform. I want to share my complete experience from start to finish - the planning, the emotions, the spiritual transformation. It was truly the journey of a lifetime!', 'Success Stories', 534, 10),
('11d01395-18e8-4ba6-a05e-64574e7fba35', 'Visa requirements and documentation guide', 'Putting together a comprehensive guide on visa requirements for Hajj from different countries. What documents do you need? How early should you apply? Common mistakes to avoid and tips to speed up the process. Let''s help each other navigate the paperwork!', 'Travel Planning', 267, 10);
